AllCops:
  NewCops: disable

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/AsciiIdentifiers:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/InverseMethods:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false
